#!/usr/bin/env bash
# Reproducible quality baseline for docs/audit/*.md.
#
# Prints one Markdown document to stdout: static metrics (scripts/audit-metrics.py),
# formatter / linter error counts, test results, and — with --coverage — line
# coverage for Rust (cargo-tarpaulin) and JS (node's built-in coverage).
#
#   scripts/audit-metrics.sh                 # static + lint + tests (~5-10 min)
#   scripts/audit-metrics.sh --no-tests      # static + lint only (~1 min)
#   scripts/audit-metrics.sh --coverage      # + coverage (adds ~15-25 min, instrumented rebuild)
#   scripts/audit-metrics.sh --embed         # also run the embed-model test leg
#
# Every count is parsed from tool output with an explicit pattern; a tool that
# fails to run is reported as `unavailable`, never as 0 (a zero that means
# "did not run" is the classic way a baseline lies).
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

RUN_TESTS=1
RUN_COVERAGE=0
RUN_EMBED=0
for arg in "$@"; do
  case "$arg" in
    --no-tests) RUN_TESTS=0 ;;
    --coverage) RUN_COVERAGE=1 ;;
    --embed) RUN_EMBED=1 ;;
    *) echo "unknown flag: $arg" >&2; exit 2 ;;
  esac
done

# Logs go next to the other tool exhaust, never into the repo.
LOG_DIR="${TMPDIR:-/tmp}/code-graph-audit-metrics"
mkdir -p "$LOG_DIR"

# Incremental builds across feature sets balloon target/ (memory:
# feedback_disk_fill_embed_builds); the CI legs run with it off as well.
export CARGO_INCREMENTAL=0

head="$(git rev-parse --short HEAD)"
echo "# Quality metrics @ \`$head\` — $(date -u +%Y-%m-%dT%H:%MZ)"
echo
echo "Generated by \`scripts/audit-metrics.sh $*\` (logs: \`$LOG_DIR\`). Re-run to compare."
echo

echo "## Static metrics"
echo
python3 scripts/audit-metrics.py
echo

echo "## Formatting and lint"
echo
echo "| Check | Errors | Command |"
echo "|---|---:|---|"

# rustfmt: one "Diff in <file>" header per differing file.
if cargo fmt --all -- --check > "$LOG_DIR/fmt.log" 2>&1; then
  fmt_n=0
else
  fmt_n=$(grep -c '^Diff in ' "$LOG_DIR/fmt.log" || true)
fi
echo "| cargo fmt --check | $fmt_n | \`cargo fmt --all -- --check\` |"

# clippy: count distinct diagnostics with a source span (the trailing
# "N warnings emitted" summary has no span and is skipped). Cargo.toml's
# [lints] promotes warnings to errors, so `level` may be either.
count_clippy() {
  local flag="$1" log="$2"
  cargo clippy $flag --all-targets --message-format=json > "$log" 2> "$log.stderr"
  python3 - "$log" <<'PY'
import json, sys
seen = set()
for line in open(sys.argv[1], encoding="utf-8", errors="replace"):
    try:
        m = json.loads(line)
    except ValueError:
        continue
    if m.get("reason") != "compiler-message":
        continue
    msg = m["message"]
    if msg.get("level") not in ("warning", "error"):
        continue
    spans = [s for s in msg.get("spans", []) if s.get("is_primary")]
    if not spans:
        continue
    s = spans[0]
    seen.add((s["file_name"], s["line_start"], (msg.get("code") or {}).get("code"), msg["message"]))
print(len(seen))
PY
}
clippy_nodefault=$(count_clippy "--no-default-features" "$LOG_DIR/clippy-nodefault.json" || echo unavailable)
echo "| cargo clippy (no-embed) | $clippy_nodefault | \`cargo clippy --no-default-features --all-targets -- -D warnings\` |"
if [ "$RUN_EMBED" = 1 ]; then
  clippy_embed=$(count_clippy "--features embed-model" "$LOG_DIR/clippy-embed.json" || echo unavailable)
  echo "| cargo clippy (embed-model) | $clippy_embed | \`cargo clippy --features embed-model --all-targets -- -D warnings\` |"
fi

# JS: there is no linter in this repo (see docs/audit); `node --check` is the
# syntax gate that exists. Counts files that fail to parse.
js_files=$(git ls-files '*.js')
js_bad=0
for f in $js_files; do
  node --check "$f" 2>> "$LOG_DIR/node-check.log" || js_bad=$((js_bad + 1))
done
echo "| node --check (all tracked .js) | $js_bad | \`git ls-files '*.js' \\| xargs -n1 node --check\` |"
echo

if [ "$RUN_TESTS" = 1 ]; then
  echo "## Tests"
  echo
  echo "| Suite | Passed | Failed | Ignored/Skipped | Wall time | Command |"
  echo "|---|---:|---:|---:|---:|---|"

  # cargo test prints one "test result:" line per test binary / doc-test run.
  # Sum the counts across all of them with explicit "N passed" patterns — a
  # field-position parse (awk -F) once reported 0 failures for a red run.
  run_cargo_tests() {
    local flag="$1" log="$2" label="$3" cmd="$4"
    local start end secs
    start=$(date +%s)
    # --no-fail-fast: a red suite must not hide the suites after it (memory:
    # feedback_ship_baseline_and_flakes — a red job masks later suites).
    cargo test $flag --no-fail-fast > "$log" 2>&1
    local rc=$?
    end=$(date +%s); secs=$((end - start))
    local passed failed ignored
    passed=$(grep -oE '[0-9]+ passed' "$log" | awk '{s+=$1} END{print s+0}')
    failed=$(grep -oE '[0-9]+ failed' "$log" | awk '{s+=$1} END{print s+0}')
    ignored=$(grep -oE '[0-9]+ ignored' "$log" | awk '{s+=$1} END{print s+0}')
    if ! grep -q '^test result:' "$log"; then
      echo "| $label | unavailable | unavailable | unavailable | ${secs}s | \`$cmd\` (exit $rc, see log) |"
    else
      echo "| $label | $passed | $failed | $ignored | ${secs}s | \`$cmd\` (exit $rc) |"
    fi
  }
  run_cargo_tests "--no-default-features" "$LOG_DIR/cargo-test-nodefault.log" \
    "Rust (no-embed)" "cargo test --no-default-features"
  if [ "$RUN_EMBED" = 1 ]; then
    CODE_GRAPH_DISABLE_MODEL_DOWNLOAD=1 run_cargo_tests "--features embed-model" "$LOG_DIR/cargo-test-embed.log" \
      "Rust (embed-model)" "CODE_GRAPH_DISABLE_MODEL_DOWNLOAD=1 cargo test --features embed-model"
  fi

  # JS: the same discovery rule as .github/workflows/ci.yml (every *.test.js
  # minus install-e2e, which needs a built release binary). TAP summary lines
  # `# pass N` / `# fail N` / `# skipped N` are the source of truth.
  js_tests=$(find claude-plugin/scripts scripts -type f -name '*.test.js' \
    | grep -vE '(^|/)install-e2e\.test\.js$' | sort)
  start=$(date +%s)
  node --test --test-concurrency=1 $js_tests > "$LOG_DIR/js-test.log" 2>&1
  js_rc=$?
  end=$(date +%s); secs=$((end - start))
  # node picks the `spec` reporter (lines prefixed "ℹ") or `tap` ("#")
  # depending on the node version and TTY; the summary keys are the same.
  js_pass=$(grep -E '^(ℹ|#) pass ' "$LOG_DIR/js-test.log" | tail -1 | awk '{print $3}')
  js_fail=$(grep -E '^(ℹ|#) fail ' "$LOG_DIR/js-test.log" | tail -1 | awk '{print $3}')
  js_skip=$(grep -E '^(ℹ|#) skipped ' "$LOG_DIR/js-test.log" | tail -1 | awk '{print $3}')
  js_n=$(echo "$js_tests" | grep -c .)
  if [ -z "$js_pass" ]; then
    echo "| JS (CI discovery set, $js_n files) | unavailable | unavailable | unavailable | ${secs}s | \`node --test --test-concurrency=1 <ci set>\` (exit $js_rc, see log) |"
  else
    echo "| JS (CI discovery set, $js_n files) | $js_pass | $js_fail | $js_skip | ${secs}s | \`node --test --test-concurrency=1 <ci set>\` (exit $js_rc) |"
  fi
  echo
fi

if [ "$RUN_COVERAGE" = 1 ]; then
  echo "## Coverage"
  echo
  # cargo-tarpaulin is installed into target/tools (not ~/.cargo/bin) so the
  # sandboxed dev box can run it: `cargo install cargo-tarpaulin --locked --root target/tools`.
  TARP="${TARPAULIN_BIN:-target/tools/bin/cargo-tarpaulin}"
  command -v cargo-tarpaulin >/dev/null 2>&1 && TARP="cargo-tarpaulin"
  if [ -x "$TARP" ] || command -v "$TARP" >/dev/null 2>&1; then
    start=$(date +%s)
    # --engine llvm: needs no llvm-tools rustup component (tarpaulin parses the
    # .profraw itself). --skip-clean + a dedicated target dir keep the
    # instrumented build from clobbering the normal one.
    "$TARP" tarpaulin --engine llvm --no-default-features --skip-clean \
      --target-dir target/tarpaulin --out json --output-dir "$LOG_DIR" \
      --timeout 600 > "$LOG_DIR/tarpaulin.log" 2>&1
    tarp_rc=$?
    end=$(date +%s); secs=$((end - start))
    if [ -f "$LOG_DIR/tarpaulin-report.json" ]; then
      python3 - "$LOG_DIR/tarpaulin-report.json" "$secs" <<'PY'
import json, sys
from collections import defaultdict
r = json.load(open(sys.argv[1]))
covered = 0
total = 0
per_dir = defaultdict(lambda: [0, 0])
per_file = []
for f in r.get("files", []):
    path = "/".join(f["path"])
    if "/src/" not in path:
        continue
    rel = path.split("/src/", 1)[1]
    c = f["covered"]
    t = f["coverable"]
    covered += c
    total += t
    d = rel.split("/")[0] if "/" in rel else "(root)"
    per_dir[d][0] += c
    per_dir[d][1] += t
    per_file.append((c / t if t else 1.0, t, rel))
pct = 100 * covered / total if total else 0
print(f"- Rust line coverage (`src/`, `--no-default-features`, tarpaulin llvm engine): **{pct:.1f}%** ({covered:,}/{total:,} lines) in {sys.argv[2]}s")
print()
print("| src module | Covered | Coverable | % |")
print("|---|---:|---:|---:|")
for d, (c, t) in sorted(per_dir.items(), key=lambda kv: kv[1][0] / kv[1][1] if kv[1][1] else 0):
    print(f"| {d} | {c:,} | {t:,} | {100 * c / t if t else 0:.1f}% |")
print()
print("Lowest-covered production files (≥100 coverable lines):")
print()
print("| % | Coverable | File |")
print("|---:|---:|---|")
for pcv, t, rel in sorted(x for x in per_file if x[1] >= 100)[:15]:
    print(f"| {100 * pcv:.1f}% | {t} | `src/{rel}` |")
PY
    else
      echo "- Rust coverage: unavailable (tarpaulin exit $tarp_rc, see $LOG_DIR/tarpaulin.log)"
    fi
  else
    echo "- Rust coverage: unavailable (cargo-tarpaulin not installed; \`cargo install cargo-tarpaulin --locked --root target/tools\`)"
  fi
  echo

  # Node's built-in coverage instruments every file the tests load; restrict the
  # report to production files (tests themselves would inflate the number).
  js_tests=$(find claude-plugin/scripts scripts -type f -name '*.test.js' \
    | grep -vE '(^|/)install-e2e\.test\.js$' | sort)
  node --test --test-concurrency=1 --experimental-test-coverage \
    --test-coverage-exclude='**/*.test.js' --test-coverage-exclude='**/node_modules/**' \
    $js_tests > "$LOG_DIR/js-coverage.log" 2>&1
  # The summary block ends with an "all files | line% | branch% | funcs%" row.
  js_cov=$(grep -E '^(ℹ|#) all files' "$LOG_DIR/js-coverage.log" | tail -1)
  if [ -n "$js_cov" ]; then
    js_line=$(echo "$js_cov" | awk -F'|' '{gsub(/ /,"",$2); print $2}')
    js_branch=$(echo "$js_cov" | awk -F'|' '{gsub(/ /,"",$3); print $3}')
    js_func=$(echo "$js_cov" | awk -F'|' '{gsub(/ /,"",$4); print $4}')
    echo "- JS line coverage (production \`.js\` loaded by the CI test set, node built-in): **${js_line}%** (branch ${js_branch}%, functions ${js_func}%)"
    echo
    echo "Lowest-covered JS production files:"
    echo
    echo "| Line % | File |"
    echo "|---:|---|"
    grep -E '^(ℹ|#) +[A-Za-z0-9_./-]+\.js +\|' "$LOG_DIR/js-coverage.log" | grep -v '\.test\.js' \
      | awk -F'|' '{f=$1; sub(/^(ℹ|#) +/,"",f); sub(/ +$/,"",f); l=$2; gsub(/ /,"",l); print l"\t"f}' \
      | sort -n | head -10 | awk -F'\t' '{printf "| %s | `%s` |\n", $1, $2}'
  else
    echo "- JS coverage: unavailable (see $LOG_DIR/js-coverage.log)"
  fi
  echo
fi
